# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{distance_measures}
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["reddavis"]
  s.date = %q{2010-12-29}
  s.description = %q{A bundle of distance measures with C extensions for the slow bits}
  s.email = %q{reddavis@gmail.com}
  s.extensions = ["ext/core/extconf.rb", "ext/euclidean_distance/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "distance_measures.gemspec",
    "ext/19_fix/19_fix.c",
    "ext/core/core.c",
    "ext/core/extconf.rb",
    "ext/euclidean_distance/euclidean_distance.c",
    "ext/euclidean_distance/extconf.rb",
    "lib/distance_measures.rb",
    "lib/distance_measures/core.bundle",
    "lib/distance_measures/cosine_similarity.rb",
    "lib/distance_measures/euclidean_distance.bundle",
    "lib/distance_measures/haversine.rb",
    "lib/distance_measures/jaccard.rb",
    "lib/distance_measures/tanimoto_coefficient.rb",
    "spec/distance_measures_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/reddavis/distance_measure}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A bundle of distance measures with C extensions for the slow bits}
  s.test_files = [
    "spec/distance_measures_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

